resources:
- name: concourse-debug
  type: git
  source:
    uri: https://github.com/divyabhargov/concourse-debug.git

- name: public_image
  type: docker-image
  source:
    repository: centos
    tag: '6'

jobs:
- name: public_image_defined_here_with_separate_task
  plan:
  - get: public_image
  - get: concourse-debug
  - task: example
    image: public_image
    file: concourse-debug/task.yml
